[package]
name = "address-miner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-client = "1.5.0"
casper-node = "1.4.8"
casper-types = "1.5.0"
